# https://github.com/marketplace/actions/go-test-coverage
# (mandatory)
# Path to coverprofile file (output of `go test -coverprofile` command).
#
# For cases where there are many coverage profiles, such as when running
# unit tests and integration tests separately, you can combine all those
# profiles into one. In this case, the profile should have a comma-separated list
# of profile files, e.g., 'cover_unit.out,cover_integration.out'.
profile: cover_unit.out

# (optional; but recommended to set)
# When specified reported file paths will not contain local prefix in the output
local-prefix: "github.com/chainalysis-oss/oslc"

# Holds coverage thresholds percentages, values should be in range [0-100]
threshold:
  # (optional; default 0)
  # The minimum coverage that each file should have
  file: 70

  # (optional; default 0)
  # The minimum coverage that each package should have
  package: 80

  # (optional; default 0)
  # The minimum total coverage project should have
  total: 85.5

# Holds regexp rules which will exclude matched files or packages
# from coverage statistics
exclude:
  # Exclude files or packages matching their paths
  paths:
    - \.pb\.go$       # excludes all protobuf generated files
    - ^mocks\/.*$     # excludes all mocks

override:
  - threshold: 9.9
    path: ^cmd\/oslc-request-server\/main.go$
  - threshold: 33.6
    path: ^cmd\/oslc-request-server\.*$
