[tools]
"aqua:FiloSottile/mkcert" = "1.4.4"
"aqua:bufbuild/buf" = "1.48.0"
"aqua:fullstorydev/grpcurl" = "1.9.2"
"aqua:goreleaser/goreleaser" = "2.5.0"
"aqua:grpc/grpc-go/protoc-gen-go-grpc" = "latest"
"aqua:protocolbuffers/protobuf-go/protoc-gen-go" = "1.36.0"
"aqua:vektra/mockery" = "2.50.1"
go = "1.23.4"
"go:github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod" = "1.8.0"
"go:github.com/go-semantic-release/semantic-release/v2/cmd/semantic-release" = "2.31.0"
"go:github.com/vladopajic/go-test-coverage/v2" = "2.11.1"
"go:golang.org/x/pkgsite/cmd/pkgsite" = "0.0.0-20241210171136-d5afb0b68716"
