#!/usr/bin/env sh
#MISE description="Check test coverage"
#MISE depends=["tests:unit", "tests:integration"]
#MISE wait_for=["tests:unit", "tests:integration"]
go-test-coverage --config=./.testcoverage.yml
