name: Acceptance Tests
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'The image to test'
        type: string
        required: true
  workflow_call:
    inputs:
      image:
        description: 'The image to test'
        type: string
        required: true

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: jdx/mise-action@249c01ba271e19fa76eede7f766161cc95ace489 # 2.1.10
        with:
          experimental: true
      - run: mise run generate:certificates
      - run: IMAGE_TO_TEST="${{ inputs.image }}" go test tests/acceptance/*.go