name: Build Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # 5.2.0
        with:
          go-version-file: "./go.mod"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build cmd/oslc_request_server -o oslc_request_server-${{ matrix.go-arch }}
      - name: Upload binaries
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # 4.5.0
        with:
          name: oslc_request_server-${{ matrix.go-arch }}
          path: oslc_request_server-${{ matrix.go-arch }}
          retention-days: 1

  collect:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download binaries
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # 4.1.8
        with:
          path: build
          pattern: oslc_request_server-*
          merge-multiple: 'true'
      - name: Generate checksums
        run: |
          cd build
          sha256sum oslc_request_server-* > checksums.txt
      - name: Prepare dist
        run: |
          mkdir dist
          mv build/checksums.txt dist/
          mv build/oslc_request_server-* dist/
      - name: Upload binaries and checksums
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # 4.5.0
        with:
          name: oslc_request_server
          path: dist
