name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    uses: chainalysis-oss/oslc/.github/workflows/reusable_build.yaml@main
    with:
      version: "unknown-dirty"
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write