name: Unit Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
permissions: read-all
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: jdx/mise-action@249c01ba271e19fa76eede7f766161cc95ace489 # 2.1.10
        with:
          experimental: true
      - run: mise run generate:certificates
      - name: Unit Tests
        uses: robherley/go-test-action@v0
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: jdx/mise-action@249c01ba271e19fa76eede7f766161cc95ace489 # 2.1.10
        with:
          experimental: true
      - run: mise run generate:certificates
      - name: generate test coverage
        run: go test ./... -coverprofile=./cover_unit.out -covermode=atomic
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
