name: Unit Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
permissions: read-all
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # 5.2.0
        with:
          go-version-file: "./go.mod"
      - name: Unit Tests
        uses: robherley/go-test-action@v0
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # 5.2.0
        with:
          go-version-file: "./go.mod"
      - name: generate test coverage
        run: go test ./... -coverprofile=./cover_unit.out -covermode=atomic
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
