name: Unit Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
permissions: read-all
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Unit Tests
        uses: robherley/go-test-action@v0
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: generate test coverage
        run: go test ./... -coverprofile=./cover_unit.out -covermode=atomic
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
